### ISSUE TITLE
Improve AND statements in Scenarios

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#82]
### Expected Behavior

for this us:
```
Given a user story text
And a category
When I create a user story with this text
Then a new user story class should be created

```
I would expect to implement the step

`(and) a category`
or something like 
`(given) and a category`

### Actual Behavior

I have to write` (given) a category`
### Steps to reproduce error

create a user story with and statement

**Comment by MarcelSchmidberger** [comment]
This should be documented in the readme

**Comment by Askir** [comment]
Not to be rude but I think this is just you being a little stupid :D 
The whole reason for And statements is to chain multiple given statements and obviously you don't want to implement a `given` step and an `and` step which do exactly the same thing just because the customer uses it as a Given step once and another time as an And step. So instead you only have to define the step once and can use And as an alias.

**Comment by MarcelSchmidberger** [comment]
Yeah in you are propably right, but I think this should be documented in the readme
